#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# exec gnome-session
# exec startkde
# exec startxfce4
# ...or the Window Manager of your choice

# Multiple envs
DEFAULT_SESSION=startxfce4

case $1 in
wmii)
	exec ck-launch-session wmii
	;;
*)
	exec $DEFAULT_SESSION
	;;
esac
